# Generated by Django 4.1.4 on 2025-02-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_start_date', models.DateField()),
                ('period_start_time', models.TimeField()),
                ('ots_count', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('watcher_count', models.IntegerField()),
            ],
        ),
    ]
